### ISSUE TITLE
New place for reference

### ISSUE THREAD

**Issue by dinhanhx** [vietanh2000april/audio-steganography-try-hard-python#1]
https://github.com/vietanh2000april/audio-steganography-try-hard-python/blob/032876d0535c5665fbbf25fb516538c0b0237b50/references/sources.txt#L1

There should be a reference section in this README.md file, https://github.com/vietanh2000april/audio-steganography-try-hard-python#readme

**Comment by vietanh2000april** [comment]
Thks O.O
